language: c
sudo: required

matrix:
        include:
                - os: linux
                  dist: trusty
                  compiler:
                          - clang
                          - gcc
                - os: osx
                  compiler:
                          - clang

# only valgrind on Linux for simplicity and speed
before_install:
        - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -y install valgrind

script: ./bootstrap.sh
