language: c
sudo: required
dist: trusty

compiler:
  - clang
  - gcc

matrix:
  include:
    - os: linux
    - os: osx

# only valgrind on Linux for simplicity and speed
addons:
  apt:
    packages:
      - valgrind

script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then TRAVIS=1 python ./bootstrap.py ; else TRAVIS=1 ./bootstrap.py; fi
