---
language: c
sudo: required
dist: trusty

compiler:
  - clang
  - gcc

matrix:
  include:
    - os: linux
    - os: osx

# only valgrind on Linux for simplicity and speed
addons:
  apt:
    packages:
      - valgrind
      - ruby
      - ruby-dev
      - python3-pip

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install python3; fi

script:
  - ./bootstrap.py
...
