language: c

compiler:
  - clang
  - gcc

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      sudo: required

# only valgrind on Linux for simplicity and speed
addons:
  apt:
    packages:
      - valgrind

script: ./bootstrap.sh
