---
language: c
sudo: required
dist: trusty

compiler:
  - clang
  - gcc

matrix:
  include:
    - os: linux
    - os: osx

# only valgrind on Linux for simplicity and speed
addons:
  apt:
    packages:
      - valgrind
      - ruby2.3
      - ruby2.3-dev

install:
  - gem install md2man

script: TRAVIS=1 ./bootstrap.sh
...
