language: c
sudo: required

compiler:
  - clang
  - gcc

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx

# only valgrind on Linux for simplicity and speed
addons:
  apt:
    packages:
      - valgrind

script: ./bootstrap.sh
